### Contents

- [EDA](#EDA)

### Header

In [1]:
# user configuration

In [1]:
# import libraries

# maths
import scipy.stats as stats
import numpy as np
import pandas as pd
#from pandas.api.types import is_numeric_dtype

# visual
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_style('darkgrid')

# html
from IPython.display import Image
from IPython.core.display import HTML

# web
import json

# others
from tqdm import tqdm
import datetime as dt
#import re
#import os

In [2]:
# file paths

folder = 'fitrec/'

input_path = '../data/1_input/' + folder
clean_path = '../data/2_clean/' + folder
preprocess_path = '../data/3_preprocess/' + folder
output_path = '../data/4_output/' + folder

### Import Data

In [3]:
# import data

file = 'endomondoHR_proper_summary.csv'
in_path = clean_path + file

df = pd.read_csv(in_path)

### Functions

### Inspect Data

In [4]:
print(df.shape)
df.head()

(167783, 26)

,id,userId,gender,sport,time_start,time_end,time_dur,lat_start,lat_end,lon_start,...,hr_avg,hr_min,hr_q1,hr_q3,hr_max,spd_avg,spd_min,spd_q1,spd_q3,spd_max
0,1,10921915.0,male,bike,1.408899e+09,1.408906e+09,126.483333,60.173349,60.173354,24.649770,...,152.650,100.0,146.0,160.0,177.0,26.162158,3.8592,19.8972,31.7313,57.4596
1,2,10921915.0,male,bike,1.408222e+09,1.408226e+09,74.000000,60.173248,60.173344,24.649855,...,147.710,100.0,140.0,156.0,174.0,27.218369,8.0820,21.8106,31.9257,54.7704
2,3,10921915.0,male,bike,1.407858e+09,1.407865e+09,112.483333,60.173262,60.173366,24.649957,...,140.554,99.0,133.0,149.0,168.0,26.050774,0.0000,20.5992,31.0365,59.2092
3,4,10921915.0,male,bike,1.407432e+09,1.407437e+09,75.316667,60.173286,60.173303,24.649874,...,147.020,99.0,140.0,155.0,178.0,26.877838,4.3272,21.4848,31.2651,57.9852
4,5,10921915.0,male,bike (transport),1.406909e+09,1.406911e+09,22.616667,60.173293,60.183756,24.649798,...,167.154,110.0,164.0,174.0,183.0,NaN,NaN,NaN,NaN,NaN

In [5]:
# Check for nulls in columns

null_cols = df.isnull().sum()
mask_null = null_cols > 0
null_cols[mask_null].sort_values(ascending=False)

spd_max    136110
spd_q3     136110
spd_q1     136110
spd_min    136110
spd_avg    136110
dtype: int64

In [6]:
df.columns

Index(['id', 'userId', 'gender', 'sport', 'time_start', 'time_end', 'time_dur',
       'lat_start', 'lat_end', 'lon_start', 'lon_end', 'alt_avg', 'alt_min',
       'alt_q1', 'alt_q3', 'alt_max', 'hr_avg', 'hr_min', 'hr_q1', 'hr_q3',
       'hr_max', 'spd_avg', 'spd_min', 'spd_q1', 'spd_q3', 'spd_max'],
      dtype='object')

In [9]:
df['sport'].value_counts()

bike                       71915
run                        70591
mountain bike              10722
bike (transport)            7757
indoor cycling              1725
walk                        1289
orienteering                 867
cross-country skiing         789
core stability training      448
fitness walking              292
skate                        271
roller skiing                238
hiking                       237
kayaking                      92
circuit training              89
weight training               74
rowing                        71
gymnastics                    66
soccer                        51
downhill skiing               48
treadmill running             28
snowshoeing                   16
swimming                      14
golf                          12
badminton                     10
horseback riding              10
elliptical                    10
tennis                         8
basketball                     8
aerobics                       7
climbing                       5
table tennis                   4
pilates                        3
snowboarding                   3
rugby                          3
stair climing                  3
squash                         1
kite surfing                   1
yoga                           1
sailing                        1
windsurfing                    1
treadmill walking              1
martial arts                   1
Name: sport, dtype: int64

In [8]:
cols = ['time_dur','alt_avg', 'alt_min','alt_q1', 'alt_q3', 'alt_max',
        'hr_avg', 'hr_min', 'hr_q1', 'hr_q3','hr_max', 
        'spd_avg', 'spd_min', 'spd_q1', 'spd_q3', 'spd_max']

df_avg = df.groupby('sport')[cols].mean()
df_avg

,time_dur,alt_avg,alt_min,alt_q1,alt_q3,alt_max,hr_avg,hr_min,hr_q1,hr_q3,hr_max,spd_avg,spd_min,spd_q1,spd_q3,spd_max
sport,,,,,,,,,,,,,,,,
aerobics,63.838095,44.808629,31.571429,41.800000,47.007143,65.428571,145.932286,81.285714,127.857143,164.000000,193.142857,NaN,NaN,NaN,NaN,NaN
badminton,67.103333,226.784800,179.700000,221.340000,235.470000,246.080000,140.237600,103.700000,131.950000,149.800000,166.100000,NaN,NaN,NaN,NaN,NaN
basketball,73.125000,43.224400,40.775000,43.100000,43.450000,44.950000,126.663000,69.750000,113.218750,143.375000,167.000000,NaN,NaN,NaN,NaN,NaN
bike,171.579353,127.664651,87.927270,108.137090,145.107318,182.687025,133.431775,85.856706,124.853504,143.302426,163.335507,27.090391,4.338433,22.787759,31.569375,47.946659
bike (transport),60.359439,223.364768,197.448803,210.923975,234.994378,262.206472,126.702738,79.705685,119.047731,135.999162,154.708264,23.408784,3.505833,20.249586,27.075343,40.676499
circuit training,64.237266,72.753622,57.215730,68.208989,77.886517,95.959551,120.585438,80.977528,109.969101,131.778090,153.449438,NaN,NaN,NaN,NaN,NaN
climbing,147.786667,858.551200,577.200000,730.400000,979.630000,1094.160000,134.794000,89.600000,118.200000,149.400000,174.000000,NaN,NaN,NaN,NaN,NaN
core stability training,77.191443,285.219983,245.750206,273.710032,297.137356,317.839795,129.315647,85.406250,120.049107,139.318080,160.437500,15.533825,2.299543,12.463371,18.110657,39.251476
cross-country skiing,107.250549,504.328833,434.983128,478.495999,530.062049,569.496462,137.602388,87.467681,129.809886,146.951521,164.197719,14.339669,1.759655,11.235321,16.978376,29.952869
downhill skiing,150.692708,1609.986020,1225.092438,1489.169953,1740.622562,1937.648333,85.424542,55.437500,72.088542,97.880208,129.083333,NaN,NaN,NaN,NaN,NaN
elliptical,41.405000,87.888640,83.720000,86.575000,89.040000,93.680000,131.963400,84.400000,124.800000,141.300000,154.800000,NaN,NaN,NaN,NaN,NaN
fitness walking,82.764098,141.471262,106.889753,130.174347,152.122378,182.260812,116.523377,73.777397,108.500856,123.829623,154.791096,7.910009,2.587680,7.101480,8.780160,20.344320
golf,122.525000,75.966133,61.516668,71.862500,79.708333,129.116667,91.381000,69.000000,85.312500,97.104167,125.166667,NaN,NaN,NaN,NaN,NaN
gymnastics,20.337374,30.040521,28.581818,29.506061,30.529545,31.600000,105.293545,72.909091,96.715909,112.704545,141.712121,NaN,NaN,NaN,NaN,NaN
hiking,148.057314,458.990114,312.293907,388.488489,529.537555,598.736328,110.858388,77.691983,100.907173,120.194093,147.189873,6.800796,2.409300,6.148125,7.550775,17.540100
horseback riding,63.706667,101.805840,88.100000,94.120000,102.265000,195.200000,140.994000,97.000000,127.700000,153.200000,175.200000,13.469501,0.000000,11.639700,16.257600,20.221200
indoor cycling,73.705720,166.076955,145.431377,159.720399,172.143458,187.007027,133.215825,84.893333,125.944058,142.430290,156.040580,27.365576,9.381110,24.211349,30.755890,40.050168
kayaking,80.678804,45.544740,34.761987,43.455884,47.560448,55.563416,122.459522,75.119565,111.288043,135.263587,156.858696,9.567574,3.174120,9.023040,10.219320,13.270680
kite surfing,137.533333,46.416000,-4.000000,31.350000,60.800000,92.000000,152.434000,76.000000,143.000000,163.250000,184.000000,NaN,NaN,NaN,NaN,NaN
martial arts,86.650000,16.913200,11.200000,13.400000,20.200000,26.600000,109.044000,75.000000,95.750000,121.000000,145.000000,NaN,NaN,NaN,NaN,NaN
mountain bike,116.749067,243.537892,181.164344,214.840902,270.912134,318.148227,135.450451,84.236896,125.790104,146.301623,166.677392,20.326192,2.392666,15.018575,25.002494,44.983224
orienteering,71.642503,92.754304,68.845966,84.674002,100.416079,120.197773,147.309128,85.238754,141.491061,155.756920,171.178777,10.734081,2.134145,9.752073,11.818473,16.180691
pilates,32.127778,11.962933,7.133333,10.600000,13.266667,15.733333,96.287333,71.000000,86.666667,105.000000,128.666667,NaN,NaN,NaN,NaN,NaN
roller skiing,78.387465,240.780068,186.647934,217.400018,262.805838,304.529638,129.870647,79.525210,120.482143,140.870798,157.079832,15.421328,2.918274,13.296174,17.604095,25.428126
rowing,63.517136,38.565746,31.651099,36.569070,40.300817,46.862324,133.885746,86.028169,122.992958,145.834507,164.042254,NaN,NaN,NaN,NaN,NaN
rugby,122.927778,110.608868,105.000000,106.000000,114.666667,136.333333,145.350000,95.666667,132.833333,159.000000,183.000000,NaN,NaN,NaN,NaN,NaN
run,107.307070,179.064443,149.316939,167.850959,189.582837,213.523872,147.102913,86.684662,142.001048,154.072035,168.602357,11.520197,3.720163,10.870201,12.233937,18.510499
sailing,54.700000,-4.306400,-15.000000,-7.850000,-0.800000,11.000000,163.934000,151.000000,161.000000,166.000000,173.000000,NaN,NaN,NaN,NaN,NaN
skate,73.765867,91.852828,73.675892,87.309096,96.290225,114.369329,120.701173,76.542435,112.951107,129.613469,147.701107,21.457228,4.956000,19.180200,23.707800,32.292300
snowboarding,174.961111,785.735216,665.133333,721.440167,843.483333,943.466667,101.116000,67.666667,83.333333,118.666667,152.666667,NaN,NaN,NaN,NaN,NaN
snowshoeing,131.190625,783.731675,725.387500,758.421875,809.437500,829.912500,125.564500,83.625000,116.609375,134.843750,156.375000,NaN,NaN,NaN,NaN,NaN
soccer,64.262418,192.759647,184.737255,189.794118,194.986275,205.917647,144.990314,96.117647,133.602941,158.176471,176.843137,NaN,NaN,NaN,NaN,NaN
squash,65.300000,275.208800,266.800000,275.000000,275.800000,282.400000,144.982000,102.000000,138.000000,154.000000,175.000000,NaN,NaN,NaN,NaN,NaN
stair climing,57.572222,190.230533,175.266667,184.625000,195.591667,211.733333,124.470000,85.666667,114.916667,134.500000,156.000000,NaN,NaN,NaN,NaN,NaN
swimming,45.569048,410.050857,390.107143,405.196429,414.378571,428.100000,122.359143,79.285714,110.767857,135.571429,149.714286,NaN,NaN,NaN,NaN,NaN
table tennis,153.500000,50.237600,49.450000,50.050000,50.350000,53.300000,87.805000,52.000000,78.125000,98.000000,123.000000,NaN,NaN,NaN,NaN,NaN
tennis,82.975000,224.686061,209.559625,221.086750,228.344750,236.965625,129.177750,90.250000,115.968750,142.500000,164.500000,NaN,NaN,NaN,NaN,NaN
treadmill running,35.416071,89.657386,74.071428,86.067857,93.257143,99.964286,145.547786,87.821429,140.258929,153.464286,161.321429,NaN,NaN,NaN,NaN,NaN
treadmill walking,17.933333,391.197200,387.800000,389.400000,393.000000,394.000000,186.644000,134.000000,178.000000,196.000000,233.000000,NaN,NaN,NaN,NaN,NaN
walk,69.046031,242.082283,216.656419,232.004142,251.791404,271.663069,102.559449,79.802172,97.098332,107.338247,127.737005,6.376824,2.479412,5.974032,6.723838,14.667565
weight training,60.077027,53.476422,42.045946,51.320946,56.462162,63.491892,111.139216,73.824324,99.202703,121.902027,153.959459,NaN,NaN,NaN,NaN,NaN
windsurfing,49.750000,1535.288350,89.000000,747.215250,2445.377500,2976.000000,132.492000,104.000000,122.000000,140.000000,173.000000,NaN,NaN,NaN,NaN,NaN
yoga,40.333333,10.693200,6.800000,8.800000,11.000000,19.400000,87.128000,69.000000,82.000000,90.000000,118.000000,NaN,NaN,NaN,NaN,NaN

### Plot Data